### ISSUE TITLE
table content 寬度為內容寬度 （Making a Bootstrap table column fit to content）

### ISSUE THREAD

**Issue by gitakachan** [gitakachan/bootstrap-issues#8]
參考：https://stackoverflow.com/questions/31184000/making-a-bootstrap-table-column-fit-to-content

```scss
table.table-fit {
  width: auto !important;
  table-layout: auto !important;

  thead th,
  tfoot th {
    width: auto !important;
  }
  tbody td {
    width: auto !important;
    &.no-border {
      border-bottom: none;
    }
  }
}
```
